language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install coveralls
  - pip install pytest
  - pip install flake8
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"

script: 
  - make lint
  - make test

after_success:
  coveralls
