language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  # coverage run --source=moscowdjango,meetup manage.py test

script: 
  make test

after_success:
  coveralls
