language: python

dist: xenial

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install coveralls
  - pip install pytest
  - pip install flake8

script:
  - make lint
  - make test

after_success:
  coveralls
